baseurl = "/"
languageCode = "en-us"
title = "Curso de R para jornalistas"
author = "Gabriela Caesar"
theme = "hugo-theme-learn"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Sobre"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/gabrielacaesar/curso-r-para-jornalistas"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/gabrielacaesar"

[params]
    description = "Curso de R para jornalistas"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "android-chrome-512x512.png"
    width = 50
    height = 50
    alt = "Logo"

